  version: "3.8"

  services:
    spigot:
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - VERSION=1.16.4
      image: spigot:latest
      ports:
        - "25565:25565"
      container_name: spigot
      volumes:
        - ./world:/minecraft/world
        - ./world_nether:/minecraft/world_nether
        - ./world_the_end:/minecraft/world_the_end
