  version: "3.8"

  services:
    spigot:
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - VERSION=1.16.4
      image: spigot:latest
      ports:
        - "25565:25565"
      container_name: spigot
      volumes:
        - type: volume
          source: world
          target: /minecraft/world

        - type: volume
          source: world_nether
          target: /minecraft/world_nether

        - type: volume
          source: world_the_end
          target: /minecraft/world_the_end

  volumes:
    world:
    world_nether:
    world_the_end:
